AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  rif - RAG with S3 Vectors and Bedrock

Globals:
  Function:
    Timeout: 300
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  RagApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: RagApi
      StageName: Prod

  RiffUploadTestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: riffuploadtestbucket

  VectorBucket:
    Type: AWS::S3Vectors::VectorBucket
    Properties:
      VectorBucketName: rag-lab-vector-store1

  VectorIndex:
    Type: AWS::S3Vectors::Index
    DependsOn: VectorBucket
    Properties:
      VectorBucketName: rag-lab-vector-store1
      IndexName: rag-lab-index1
      Dimension: 1024
      DistanceMetric: cosine
      DataType: float32
      MetadataConfiguration:
        NonFilterableMetadataKeys:
          - text
          - text-metadata
          - AMAZON_BEDROCK_TEXT
          - AMAZON_BEDROCK_METADATA
          - x-amz-bedrock-kb-source-uri
          - x-amz-bedrock-kb-document-page-number
          - document_metadata
          - source_metadata
          - content_metadata
          - extraction_metadata

  ChunkDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: chunk_docs/
      Handler: chunk_data.chunk
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: !GetAtt RAGProcessingLambdaRole.Arn
      Events:
        S3PutEvent:
          Type: S3
          Properties:
            Bucket: !Ref RiffUploadTestBucket
            Events: s3:ObjectCreated:Put

  PromptBedRockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: prompt_bedrock/
      Handler: prompt_bd.prompt
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Events:
        PromptRagEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RagApi
            Path: /prompt-rag
            Method: post

  RetrieveAndConverseWithBedRockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: retrieve_converse/
      Handler: retrieve_converse.retrieve_kb_chunk
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Events:
        RetrieveEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RagApi
            Path: /retrieve-converse
            Method: post

  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: riff-lambda-exec-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: riff-lambda-permissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:*
                  - aoss:*
                  - iam:PassRole
                  - kms:Decrypt
                  - logs:*
                  - s3:*
                  - ssm:GetParameter
                Resource: "*"

  RAGProcessingLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: RAGProcessingLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RAGLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - bedrock:*
                  - aoss:*
                  - ssm:GetParameter
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  BedrockKBExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BedrockKBExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3VectorsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3vectors:PutVectors
                  - s3vectors:QueryVectors
                  - s3vectors:GetVectors
                  - s3vectors:DeleteVectors
                  - s3vectors:ListIndexes
                  - s3vectors:DescribeIndex
                  - bedrock:*
                  - s3:*
                Resource: "*"

  # Bedrock Knowledge Base and Data Source
  MyBedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: RiffKnowledgeBase
      RoleArn: !GetAtt BedrockKBExecutionRole.Arn
      Description: Bedrock KB backed by S3 Vectors
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v2:0
      StorageConfiguration:
        Type: S3_VECTORS
        S3VectorsConfiguration:
          IndexArn: !Sub "arn:aws:s3vectors:${AWS::Region}:${AWS::AccountId}:bucket/rag-lab-vector-store1/index/rag-lab-index1"

  MyBedrockDataSource:
    Type: AWS::Bedrock::DataSource
    # DependsOn: MyBedrockKnowledgeBase
    Properties:
      KnowledgeBaseId: !Ref MyBedrockKnowledgeBase
      Name: S3DataSource
      Description: S3 data source for knowledge base
      DataSourceConfiguration:
        Type: S3
        S3Configuration:
          BucketArn: !GetAtt RiffUploadTestBucket.Arn

  BedrockKBIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /rag-lab/knowledgebase/id
      Type: String
      Value: !Ref MyBedrockKnowledgeBase

  BedrockKBDataSourceIdParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /rag-lab/datasource/id
      Type: String
      Value: !Ref MyBedrockDataSource

  RAGGuardrail:
    Type: AWS::Bedrock::Guardrail
    Properties:
      Name: rag-lab-guardrail
      Description: "Guardrail for RAG application content filtering"
      ContentPolicyConfig:
        FiltersConfig:
          - Type: "HATE"
            InputStrength: "MEDIUM"
            OutputStrength: "MEDIUM"
          - Type: "INSULTS"
            InputStrength: "MEDIUM"
            OutputStrength: "MEDIUM"
          - Type: "SEXUAL"
            InputStrength: "HIGH"
            OutputStrength: "HIGH"
          - Type: "VIOLENCE"
            InputStrength: "MEDIUM"
            OutputStrength: "MEDIUM"
          - Type: "MISCONDUCT"
            InputStrength: "MEDIUM"
            OutputStrength: "MEDIUM"
          - Type: "PROMPT_ATTACK"
            InputStrength: "HIGH"
            OutputStrength: "NONE"
      SensitiveInformationPolicyConfig:
        PiiEntitiesConfig:
          - Type: "EMAIL"
            Action: "ANONYMIZE"
          - Type: "PHONE"
            Action: "ANONYMIZE"
          - Type: "CREDIT_DEBIT_CARD_NUMBER"
            Action: "BLOCK"
      TopicPolicyConfig:
        TopicsConfig:
          - Name: "InvestmentAdvice"
            Definition: "Investment advice and financial recommendations"
            Examples:
              - "What stocks should I buy?"
              - "Should I invest in crypto?"
              - "Give me financial planning tips."
              - "Give me amazon stock advice."
            Type: "DENY"
      BlockedInputMessaging: "Sorry, your input contains content that violates our usage policy."
      BlockedOutputsMessaging: "Sorry, I cannot provide that information due to content policy restrictions."

  # Create a version of the guardrail
  RAGGuardrailVersion:
    Type: AWS::Bedrock::GuardrailVersion
    Properties:
      GuardrailIdentifier: !Ref RAGGuardrail
      Description: "Version 1 of RAG guardrail"

  # Store guardrail ID in Parameter Store
  GuardrailIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /rag-lab/bedrock/guardrail-id
      Type: String
      Value: !Ref RAGGuardrail
      Description: "Bedrock Guardrail ID for RAG application"

  # Store guardrail version in Parameter Store
  GuardrailVersionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /rag-lab/bedrock/guardrail-version
      Type: String
      Value: !GetAtt RAGGuardrailVersion.Version
      Description: "Bedrock Guardrail Version for RAG application"
